name: 360events.co
favicon: null
layout_spectrum: 0.933885162230581
typography_spectrum: 0.9543907437473536
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6601790222339332
  lightness: 0.15486318990588188
  saturation: 0.33357619028538465
  rhythmicContrast: 0.35276765446178615
purpose: []
